name: CD

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-22.04
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: api-go
        uses: actions/checkout@v3
