# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      HOST: localhost
      USER: root
      PASSWORD: root
      DBNAME: root
      PORT: 5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build-DB
        run: docker compose build

      - name: Create-DB
        run: docker compose up -d

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v main.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: api-go
          path: main

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deply_ec2:
    needs: build
    uses: ./.github/workflows/ec2.yml
    secrets: inherit
